### ISSUE TITLE
Issue after many "repeat".

### ISSUE THREAD

**Issue by zelogik** [thekief/s1t-ledcontrol#1]
Hello,

Compiled a debug version of this executable, scp to a libreelec installation, and running alternatively :
```
# s1t-ledcontrol -m off
# s1t-ledcontrol -m (rainbow|colour-cycle|auto) -b 1 -s 0
```
wait 2sec(or more)
```
# s1t-ledcontrol -m off
# s1t-ledcontrol -m (rainbow|colour-cycle|auto) -b 1 -s 0
```
repeat...

Atfer random "repeat" The command don´t control the led anymore. the led got stuck on the last working state, only way to get it working is to power cycle the T9plus|pro, the reboot is not enougth.

The role of this working mode, was to be able to put glowing led at idle, and shutting down led when playing video.

ie: I haven´t tried with python as Libreelec don´t have serial module.
Regards

**Comment by thekief** [comment]
I will take a look at it. Could you please check if the following changes something:

```python
import serial
import time
s=serial.Serial("<path to the port>", 10000)
s.write(b'\xfa')
time.sleep(0.005)
s.write(b'\x04')
time.sleep(0.005)
s.write(b'\x05')
time.sleep(0.005)
s.write(b'\x05')
time.sleep(0.005)
s.write(b'\x08')
s.close()
```

```bash 
#!/bin/bash

# create a virtual environment
python3 -m venv s1t
source s1t/bin/activate

# install the required depenency
pip install pyserial

sudo s1t/bin/python test.py
```

These are the steps to execute the script in the original Reddit post.

**Comment by zelogik** [comment]
Yes i know, but as I have said, on LibreElec distro, I don't know how to install python3-pyserial (or import it) or even have a working venv ... pip is not available too... I will test later on a different distro.
LibreElec is "almost" a read-only distro, and many "dev" feature don´t exist here...

Edit1:` I will test if increasing/change the "delay" of 5ms will change something, or some "ugly" timeout just after the connection.

Edit2: is your setup working well ? repeat -m off / -m {breathing|auto|...} works each time ?
Regards

**Comment by zelogik** [comment]
So.. was able to install pyserial on libreelec (easier than thinking), and I have off / breathing 10 times without any problems.
It's not hardware, the rust version seem to don´t get the right timing...

**Comment by thekief** [comment]
Just got home and did a quick test and the code seems to work on my system. It kinda felt like it got a bit "stuck" on the first tries, not reacting particularly fast, though.

This is how I tested it

```shell
#!/bin/bash

for i in {1..50}
do
  echo "Run no. $i"

  <path_to_exec> -m off
  <path_to_exec> -m auto -b 1 -s 1 -d  /dev/ttyUSB0
  sleep 2
done
```

The notation used in your first command `(rainbow|colour-cycle|auto)`  is regex-like *aka* you choose only one of these values right?

**Comment by thekief** [comment]
>  It's not hardware, the rust version same to don´t get the right timing...

Could you send me your rust version please (`rustc --version`) and which target you chose.

**Comment by zelogik** [comment]
I have wrote a really quick&dirty code in C (thanks ChatGPT :p) to check and this one work: (of course the pattern is static)
```
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <sys/ioctl.h>

void delay(int milliseconds) {
    usleep(milliseconds * 1000); // usleep uses microseconds
}

int set_custom_baud(int fd, speed_t baud) {
    struct termios tty;

    if (tcgetattr(fd, &tty) != 0) {
        perror("Error getting serial port attributes");
        return -1;
    }

    // Set the custom baud rate
    cfsetospeed(&tty, baud);
    cfsetispeed(&tty, baud);

    if (tcsetattr(fd, TCSANOW, &tty) != 0) {
        perror("Error setting serial port attributes");
        return -1;
    }

    if (ioctl(fd, TIOCSSERIAL, &tty) < 0) {
        perror("Error setting custom baud rate using ioctl");
        return -1;
    }

    return 0;
}

int main() {
    const char *serialPort = "/dev/ttyUSB0";
    int fd = open(serialPort, O_WRONLY | O_NOCTTY | O_SYNC);

    if (fd == -1) {
        perror("Error opening serial port");
        return 1;
    }

    // Set a custom baud rate of 10000 if supported
    if (set_custom_baud(fd, 10000) != 0) {
        close(fd);
        return 1;
    }

    // Set other serial port settings (8N1)
    struct termios tty;
    if (tcgetattr(fd, &tty) != 0) {
        perror("Error getting serial port attributes");
        close(fd);
        return 1;
    }

    tty.c_cflag = (tty.c_cflag & ~CSIZE) | CS8;
    tty.c_cflag &= ~PARENB;
    tty.c_cflag &= ~CSTOPB;
    tty.c_cflag &= ~CRTSCTS;  // Disable hardware flow control

    if (tcsetattr(fd, TCSANOW, &tty) != 0) {
        perror("Error setting serial port attributes");
        close(fd);
        return 1;
    }

    // Send the specified pattern
    char pattern[] = {0xFA, 0x01, 0x01, 0x01, 0xFD};
    for (int i = 0; i < sizeof(pattern) / sizeof(pattern[0]); ++i) {
        if (write(fd, &pattern[i], 1) != 1) {
            perror("Error writing to serial port");
            break;
        }
        delay(5); // Wait for 5 milliseconds
    }

    close(fd);

    return 0;
}
```

And first got the same "behaviour" to your rust version when the C code was with standard 9600 baud rate.
Maybe some board are more sensitive to 9600vs10000 baud rate, and I don´t know how rust library manage non standard speed.

Ie: I'm not at work anymore, and I don´t have the rust platform here to send you the version/target.
Ie2: yes my test pattern was:
-m off
wait 1sec or more
-m breathing 
wait 2sec or more
-m off
wait 1sec or more
-m breathing -b 2 -s 2
...
repeat
...
Don't work anymore...

And next test was with another parameter like : -m colour-cycle -b 2 -s 2
etc...

**Comment by zelogik** [comment]
rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)

The target: x86_64-unknown-linux-musl

**Comment by thekief** [comment]
Thank you. I will also check the MCU. From what I have gathered so far, a baud rate of 10000 is **REALLY** unusual. The common rates in this area are 9600 and 14400. It could very likely be that they used a wrong baud rate.

**Comment by zelogik** [comment]
I use to play many time with serial port (arduino/console) etc... and yes 10000baud is not standard at all but what the manufacturer/builder have made. 
And I don´t know how the rust implementation of serial accept non standard speed. 
On the other side, it's possible that each led controller are more tolerant to accept B9600 or not, depending of the hardware version.

**Comment by thekief** [comment]
Sorry for my late reply. I opened up my T9 Pro Plus and checked the chip on the board (see the photo). 

![image](https://github.com/thekief/s1t-ledcontrol/assets/90185239/0deef07f-7545-4cce-b608-f56f19313e67)

It uses a CH340N and according to the data sheet, it supports following baud rates, among others:

`... , 600, 4800, 9600, 14400, 19200, ...`

So, the driver has it wrong in the first place. What I find quite a bit more concerning is the MCU next to the CH340N seems to be reused, with the identification being scrapped off. 

I will add a new flag to allow the modification of the baud rate.

**Comment by thekief** [comment]
I will close this issue. I just got the information that there will be a fix with in the `serialport` library that addresses the issue that arises due to the baud rate.
